netliva_symfony_comments_list:
    path:     /comments/list/{group}/{listType}/{page}
    defaults: { _controller: NetlivaCommentBundle:Comments:list, page: 1 }

netliva_symfony_comments_create:
    path:     /comments/create
    defaults: { _controller: NetlivaCommentBundle:Comments:create }
    methods: [POST]

netliva_symfony_comments_history:
    path:     /comments/history/{id}
    defaults: { _controller: NetlivaCommentBundle:Comments:history }

netliva_symfony_comments_update:
    path:     /comments/update/{viewtype}/{id}
    defaults: { _controller: NetlivaCommentBundle:Comments:update }
    methods: [POST, PUT]

netliva_symfony_new_collaborators:
    path:     /collaborators/create/{group}
    defaults: { _controller: NetlivaCommentBundle:Comments:createCollaborators }
    methods: [POST, PUT]

netliva_symfony_remove_me:
    path:     /collaborators/remove/{group}
    defaults: { _controller: NetlivaCommentBundle:Comments:removeCollaborators }
    methods: [POST, PUT]

netliva_symfony_comments_delete:
    path:     /comments/delete/{id}
    defaults: { _controller: NetlivaCommentBundle:Comments:delete }
    methods: [POST, DELETE]

netliva_symfony_reaction_add:
    path:     /comments/reaction/add/{id}
    defaults: { _controller: NetlivaCommentBundle:Reactions:add }
    methods: [POST]
netliva_symfony_reaction_history:
    path:     /comments/reaction/history/{id}
    defaults: { _controller: NetlivaCommentBundle:Reactions:history }
    methods: [POST]
