services:
    Netliva\CommentBundle\Services\CommentServices:
        class: Netliva\CommentBundle\Services\CommentServices
        public: false
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: twig.extension }

    netliva_commenter:
        alias: Netliva\CommentBundle\Services\CommentServices
        public: true
        
    Netliva\CommentBundle\Services\CacheUpdaterServices:
        class: Netliva\CommentBundle\Services\CacheUpdaterServices
        public: false
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    netliva_commenter_cacheUpdater:
        alias: Netliva\CommentBundle\Services\CacheUpdaterServices
        public: true

    netliva_commenter.comments_controller:
        class: Netliva\CommentBundle\Controller\CommentsController
        arguments: ["@event_dispatcher"]
        
    netliva_commenter.cacheClear:
        class: Netliva\CommentBundle\EventListener\CacheClearEventListener
        arguments: [ "@service_container", "@netliva_commenter_cacheUpdater"]
        tags:
            - { name: 'doctrine.event_listener', event: 'postPersist', connection: 'default' }
            - { name: 'doctrine.event_listener', event: 'postUpdate', connection: 'default' }
            - { name: 'doctrine.event_listener', event: 'preRemove', connection: 'default' }
