services:
    Netliva\CommentBundle\Services\CommentServices:
        class: Netliva\CommentBundle\Services\CommentServices
        public: false
        arguments: ["@doctrine.orm.entity_manager", "@twig"]
        tags:
            - { name: twig.extension }

    netliva.commenter:
        alias: Netliva\CommentBundle\Services\CommentServices
        public: true

    netliva_commenter.comments_controller:
        class: Netliva\CommentBundle\Controller\CommentsController
        arguments: ["@event_dispatcher"]
