services:
    Netliva\CommentBundle\Services\CommentServices:
        public: false
        arguments: ["@doctrine.orm.entity_manager", "@twig"]
        tags:
            - { name: twig.extension }

    netliva.commenter:
        alias: Netliva\CommentBundle\Services\CommentServices
        public: true
