services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Netliva\CommentBundle\Controller\:
        resource: '../../Controller/'
        tags: [ 'controller.service_arguments' ]
        
    Netliva\CommentBundle\Services\CommentServices:
        class: Netliva\CommentBundle\Services\CommentServices
        tags:
            - { name: twig.extension }
        
    Netliva\CommentBundle\Services\:
        resource: '../../Services/'
        
    netliva_commenter.cacheClear:
        class: Netliva\CommentBundle\EventListener\CacheClearEventListener
        tags:
            - { name: 'doctrine.event_listener', event: 'postPersist', connection: 'default' }
            - { name: 'doctrine.event_listener', event: 'postUpdate', connection: 'default' }
            - { name: 'doctrine.event_listener', event: 'preRemove', connection: 'default' }
